name: JAVA, PYTHON, C, and JAVASCRIPT
googleURL: https://www.instructionalsolutions.com/blog/what-is-technical-writing
topics/historyofTechWriting: https://ashviruvi09.github.io/Ramya_Silver_TWT/topics/historyofTechWriting